# cloudbuild.yaml — validated for Cloud Build Triggers
# Builds, pushes, and deploys your SAM model to Cloud Run

substitutions:
  _AR_HOSTNAME: 'europe-west1-docker.pkg.dev'
  _AR_PROJECT_ID: 'lofty-voyage-477911-m6'
  _AR_REPOSITORY: 'cloud-run-source-deploy'
  _DEPLOY_REGION: 'europe-west1'
  _PLATFORM: 'managed'
  _SERVICE_NAME: 'deploy'
  _TRIGGER_ID: '46310ca3-3f21-444c-b59b-403ff8109133'

steps:
  # Step 1 — Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      [
        'build',
        '-t',
        '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest',
        '.'
      ]

  # Step 2 — Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      [
        'push',
        '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest'
      ]

  # Step 3 — Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', '${_SERVICE_NAME}',
        '--image', '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest',
        '--region', '${_DEPLOY_REGION}',
        '--platform', '${_PLATFORM}',
        '--allow-unauthenticated',
        '--memory', '8Gi',
        '--cpu', '2',
        '--timeout', '900'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
